### ISSUE TITLE
[skip ci] problem when multiple commits pushed at once

### ISSUE THREAD

**Issue by Veikkosuhonen** [HRemonen/CommitSense#5]
<img width="1532" alt="image" src="https://github.com/HRemonen/CommitSense/assets/54055199/725d9d7b-cb16-4d36-9bc0-f1e94e97b13f">

If the latest commit has [skip ci], then actions not run even though previous to it should trigger actions. This is fakd, no idea how to fix. Probably should just put [skip ci] thing behind config and have it off by default

**Comment by HRemonen** [comment]
Yes implement on #3
